// frontend/src/views/Favorites.vue
<template>
  <div class="p-4">
    <h2 class="text-2xl font-semibold text-center">Sách Yêu Thích</h2>
    <p class="text-lg mb-6 text-center text-gray-700">
      Danh sách giá sách được tôi tuyển chọn để sắp xếp tất cả những cuốn sách yêu thích.
    </p>

    <div v-if="books.length === 0" class="text-gray-500 text-center">
      Chưa có sách nào được yêu thích.
    </div>

    <div class="grid grid-cols-2 md:grid-cols-5 gap-6">
      <div
        v-for="book in books"
        :key="book._id"
        class="shadow-md p-0 flex flex-col justify-between relative overflow-hidden"
      >
        <!-- Ảnh -->
        <div class="relative">
          <img
            :src="book.image"
            alt="Book"
            class="w-full h-96 object-cover cursor-pointer"
            @click="goToDetail(book._id)"
          />
          <button
            @click="toggleFavorite(book, (id) => books = books.filter(b => b._id !== id))"
            class="absolute top-2 right-2 bg-white bg-opacity-70 rounded-full p-2"
            title="Bỏ khỏi yêu thích"
          >
            <font-awesome-icon
              :icon="[isFavorite(book._id) ? 'fas' : 'far', 'heart']"
              :class="isFavorite(book._id) ? 'text-red-500' : 'text-black'"
            />
          </button>
        </div>

        <!-- Thông tin -->
        <div class="p-3">
          <h2 class="font-bold text-sm mt-1 line-clamp-2">{{ book.title }}</h2>
          <p class="text-green-600 text-sm font-semibold mt-2">
            {{ book.price.toLocaleString() }}₫
          </p>

          <!-- Nút thêm vào giỏ -->
          <button
            @click="addToCart(book)"
            class="mt-4 border border-gray-300 text-base px-5 py-2 rounded-2xl hover:border-gray-500 transition"
          >
            Thêm vào giỏ
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useCart } from '@/composables/useCart'
import { useFavorites } from '@/composables/useFavorites'

const router = useRouter()
const books = ref([])

const { addToCart } = useCart()
const { favorites, fetchFavorites, toggleFavorite, isFavorite } = useFavorites()

const goToDetail = (id) => {
  router.push(`/books/${id}`)
}

onMounted(async () => {
  const favoriteBooks = await fetchFavorites()
  books.value = favoriteBooks || []
})
</script>

// frontend-react/src/views/Favorites.jsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useCart } from '../composables/useCart';
import { useFavorites } from '../composables/useFavorites';

const Favorites = () => {
  const navigate = useNavigate();
  const [books, setBooks] = useState([]);

  const { addToCart } = useCart();
  const { fetchFavorites, toggleFavorite, isFavorite } = useFavorites();

  useEffect(() => {
    const loadFavorites = async () => {
      const favoriteBooks = await fetchFavorites();
      setBooks(favoriteBooks || []);
    };
    loadFavorites();
  }, [fetchFavorites]);

  const handleToggleFavorite = async (book) => {
    // Gọi hàm toggleFavorite và truyền callback để tự xoá khỏi màn hình hiện tại
    await toggleFavorite(book, (id) => {
      setBooks((prevBooks) => prevBooks.filter((b) => b._id !== id));
    });
  };

  return (
    <div className="p-4 min-h-screen max-w-7xl mx-auto">
      <h2 className="text-2xl font-semibold text-center mt-6">Sách Yêu Thích</h2>
      <p className="text-lg mb-10 text-center text-gray-700">
        Danh sách giá sách được tôi tuyển chọn để sắp xếp tất cả những cuốn sách yêu thích.
      </p>

      {books.length === 0 ? (
        <div className="text-gray-500 text-center text-xl mt-10">
          Chưa có sách nào được yêu thích.
        </div>
      ) : (
        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-6">
          {books.map((book) => (
            <div
              key={book._id}
              className="shadow-md rounded-lg flex flex-col justify-between relative overflow-hidden bg-white border"
            >
              {/* Ảnh */}
              <div className="relative group">
                <img
                  src={book.image?.startsWith('http') ? book.image : `http://localhost:5000${book.image}`}
                  alt="Book"
                  className="w-full h-80 object-cover cursor-pointer transition-transform duration-300 group-hover:scale-105"
                  onClick={() => navigate(`/books/${book._id}`)}
                />
                <button
                  onClick={() => handleToggleFavorite(book)}
                  className="absolute top-2 right-2 bg-white bg-opacity-80 rounded-full p-2 hover:bg-gray-100 transition shadow"
                  title="Bỏ khỏi yêu thích"
                >
                  <FontAwesomeIcon
                    icon={[isFavorite(book._id) ? 'fas' : 'far', 'heart']}
                    className={isFavorite(book._id) ? 'text-red-500' : 'text-black'}
                  />
                </button>
              </div>

              {/* Thông tin */}
              <div className="p-4 flex flex-col flex-grow">
                <h2 className="font-bold text-sm mt-1 line-clamp-2 h-10">{book.title}</h2>
                <p className="text-green-600 text-sm font-semibold mt-2 mb-4">
                  {book.price.toLocaleString('vi-VN')}₫
                </p>

                {/* Nút thêm vào giỏ */}
                <button
                  onClick={() => addToCart(book)}
                  className="mt-auto w-full py-2 hover-flip-btn rounded"
                >
                  Thêm vào giỏ
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default Favorites;
