// frontend/src/views/Profile.vue
<template>
  <div class="flex flex-col md:flex-row gap-6 p-4">
    <!-- LEFT SIDE MENU -->
    <div class="w-full md:w-1/3 bg-white rounded-xl shadow p-4 space-y-2">
      <div :class="tab === 'info' ? activeClass : inactiveClass" @click="tab = 'info'">
        Thông tin của tôi
      </div>
      <div :class="tab === 'security' ? activeClass : inactiveClass" @click="tab = 'security'">
        Email và mật khẩu
      </div>
      <div :class="tab === 'address' ? activeClass : inactiveClass" @click="tab = 'address'">
        Địa chỉ giao hàng
      </div>
    </div>

    <!-- RIGHT SIDE CONTENT -->
    <div class="w-full md:w-2/3 bg-white rounded-xl shadow p-6">
      <!-- TAB: THÔNG TIN CỦA TÔI -->
      <div v-if="tab === 'info'" class="space-y-6">
        <h2 class="text-2xl font-bold text-gray-800">Cập nhật thông tin</h2>

        <div class="flex items-center gap-4">
          <img :src="preview || `/${user.avatar}`" class="w-24 h-24 rounded-full object-cover border" />
          <input type="file" @change="onFileChange" />
        </div>

        <div>
          <label class="font-medium block mb-1">Tên người dùng</label>
          <input v-model="form.name" class="input-style" type="text" />
        </div>

        <button @click="updateProfile" class="btn-primary">Lưu thay đổi</button>
      </div>

      <!-- TAB: EMAIL VÀ MẬT KHẨU -->
      <div v-else-if="tab === 'security'" class="space-y-6">
        <h2 class="text-2xl font-bold text-gray-800">Bảo mật tài khoản</h2>

        <!-- EMAIL -->
        <div class="space-y-4">
          <div class="flex items-center gap-3 mb-2">
            <font-awesome-icon :icon="['fas', 'envelope']" class="text-red-500 text-xl" />
            <span class="text-base text-3xl font-semibold text-gray-800">{{ user.email }}</span>
          </div>

          <label class="block text-sm font-medium text-gray-700 mb-1">Thay đổi gmail của tôi</label>
          <input
              v-model="newEmail"
              type="email"
              name="new_email_custom_123"
              placeholder="Nhập email mới"
              autocomplete="off"
              class="input-style mb-3"
              @focus="newEmail = ''"
            />

          <button @click="updateEmail" class="btn-primary" :disabled="loadingEmail">
            <span v-if="loadingEmail"> Đang lưu... </span>
            <span v-else> Lưu </span>
          </button>
        </div>

        <!-- PASSWORD -->
        <div class="space-y-4">
          <div>
            <label class="font-medium block mb-1">Thay đổi mật khẩu</label>
            <input
              v-model="form.currentPassword"
              placeholder="Nhập mật khẩu hiện tại"
              type="password"
              autocomplete="new-password"
              name="current_password_custom"
              class="input-style"
            />
          </div>

          <div>
            <label class="font-medium block mb-1">Mật khẩu mới</label>
            <input
              v-model="form.newPassword"
              placeholder="Nhập mật khẩu mới"
              type="password"
              autocomplete="new-password"
              name="new_password_custom"
              class="input-style"
            />
          </div>

          <button @click="changePassword" class="btn-primary">Lưu</button>
          <p v-if="message" :class="messageClass">{{ message }}</p>
        </div>
      </div>

      <!-- TAB: ĐỊA CHỈ GIAO HÀNG -->
      <div v-else-if="tab === 'address'" class="space-y-6">
        <h2 class="text-2xl font-bold text-gray-800">Địa chỉ giao hàng</h2>

        <div class="grid grid-cols-2 gap-4">
          <div>
            <label class="block font-medium mb-1">Họ và tên người nhận</label>
            <input v-model="addressForm.fullName" placeholder="Nhập họ và tên" class="input-style" />
          </div>
          <div></div>
        </div>

        <div>
          <label class="block font-medium mb-1">Địa chỉ nhà</label>
          <input v-model="addressForm.street" placeholder="Nhập địa chỉ nhà" class="input-style" />
        </div>

        <div class="grid grid-cols-2 gap-4">
          <div>
            <label class="block font-medium mb-1">Quận / Huyện</label>
            <input v-model="addressForm.district" placeholder="Nhập quận / huyện" class="input-style" />
          </div>
          <div>
            <label class="block font-medium mb-1">Thành phố</label>
            <input v-model="addressForm.city" placeholder="Nhập thành phố" class="input-style" />
          </div>
        </div>

        <div>
          <label class="block font-medium mb-1">Số điện thoại</label>
          <input v-model="addressForm.phone" placeholder="Nhập số điện thoại" class="input-style" />
        </div>

        <div>
          <button @click="saveAddress" class="btn-primary">Lưu địa chỉ</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import axios from 'axios'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

const tab = ref('info')
const user = ref({ name: '', email: '', avatar: '' })
const token = localStorage.getItem('token')



const activeClass = 'bg-blue-100 font-semibold p-2 rounded cursor-pointer'
const inactiveClass = 'p-2 rounded cursor-pointer hover:bg-gray-100'

const form = ref({
  name: '',
  email: '',
  currentPassword: '',
  newPassword: '',
  avatar: null
})

const preview = ref(null)
const message = ref('')
const messageClass = ref('')
const newEmail = ref('')
const loadingEmail = ref(false)

// Load user profile
onMounted(async () => {
  const res = await axios.get('/api/users/me', {
    headers: { Authorization: `Bearer ${token}` }
  })
  user.value = res.data
  form.value.name = user.value.name
  form.value.email = user.value.email
  newEmail.value = user.value.email

  // Load address
  try {
    const res = await axios.get('/api/addresses', {
      headers: { Authorization: `Bearer ${token}` }
    })
    if (res.data.length > 0) {
      const addr = res.data[0]
      addressForm.value = {
        fullName: addr.fullName,
        phone: addr.phone,
        street: addr.street,
        district: addr.district,
        city: addr.city
      }
      addressId.value = addr._id
    }
  } catch (err) {
    console.error('Không thể tải địa chỉ:', err)
  }
})

function onFileChange(e) {
  const file = e.target.files[0]
  if (file) {
    preview.value = URL.createObjectURL(file)
    form.value.avatar = file
  }
}

async function updateProfile() {
  try {
    const formData = new FormData()
    formData.append('name', form.value.name)
    if (form.value.avatar) formData.append('avatar', form.value.avatar)

    const res = await axios.put('/api/users/me', formData, {
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'multipart/form-data'
      }
    })

    user.value = res.data.user
    localStorage.setItem('user', JSON.stringify(res.data.user))
    window.location.reload()
  } catch (err) {
    message.value = 'Có lỗi xảy ra!'
    messageClass.value = 'text-red-600'
  }
}

async function changePassword() {
  if (!form.value.currentPassword || !form.value.newPassword) {
    message.value = 'Vui lòng nhập đầy đủ thông tin'
    messageClass.value = 'text-red-600'
    return
  }

  try {
    const res = await axios.put('/api/users/change-password', {
      currentPassword: form.value.currentPassword,
      newPassword: form.value.newPassword
    }, {
      headers: { Authorization: `Bearer ${token}` }
    })

    if (res.data.success) {
      message.value = 'Đổi mật khẩu thành công'
      messageClass.value = 'text-green-600'
      form.value.currentPassword = ''
      form.value.newPassword = ''
    } else {
      message.value = 'Nhập sai mật khẩu cũ'
      messageClass.value = 'text-red-600'
    }
  } catch (err) {
    message.value = 'Lỗi đổi mật khẩu'
    messageClass.value = 'text-red-600'
  }
}

const updateEmail = async () => {
  if (!newEmail.value || newEmail.value === user.value.email) {
    alert('Vui lòng nhập email mới hợp lệ!')
    return
  }

  try {
    loadingEmail.value = true
    await axios.put('/api/users/update-email', { email: newEmail.value }, {
      headers: { Authorization: `Bearer ${token}` }
    })

    user.value.email = newEmail.value
    localStorage.setItem('user', JSON.stringify(user.value))
    alert('Email đã được cập nhật!')
  } catch (err) {
    alert('Lỗi: ' + (err.response?.data?.msg || 'Không thể cập nhật email'))
  } finally {
    loadingEmail.value = false
  }
}

// ===== ĐỊA CHỈ GIAO HÀNG ===== //
const addressForm = ref({
  fullName: '',
  phone: '',
  street: '',
  district: '',
  city: ''  
})

const addressId = ref(null)

const saveAddress = async () => {
  try {
    if (addressId.value) {
      await axios.put(`/api/addresses/${addressId.value}`, addressForm.value, {
        headers: { Authorization: `Bearer ${token}` }
      })
    } else {
      const res = await axios.post('/api/addresses', addressForm.value, {
        headers: { Authorization: `Bearer ${token}` }
      })
      addressId.value = res.data._id
    }
    alert('Lưu địa chỉ thành công!')
  } catch (err) {
    console.error(err)
    alert('Lỗi khi lưu địa chỉ!')
  }
}
</script>

<style scoped>
.input-style {
  @apply mt-1 block w-full border border-gray-300 rounded p-2 focus:outline-none focus:ring-2 focus:ring-blue-500;
}
.btn-primary {
  @apply bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition;
}
</style>

// frontend-react/src/views/Profile.jsx
import { useState, useEffect } from 'react';
import axios from 'axios';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

const Profile = () => {
  const [tab, setTab] = useState('info');
  const [user, setUser] = useState({ name: '', email: '', avatar: '' });
  const [form, setForm] = useState({ name: '', email: '', currentPassword: '', newPassword: '', avatar: null });
  const [addressForm, setAddressForm] = useState({ fullName: '', phone: '', street: '', district: '', city: '' });

  const [preview, setPreview] = useState(null);
  const [message, setMessage] = useState('');
  const [messageClass, setMessageClass] = useState('');
  const [newEmail, setNewEmail] = useState('');
  const [loadingEmail, setLoadingEmail] = useState(false);
  const [addressId, setAddressId] = useState(null);

  const token = localStorage.getItem('token');
  const activeClass = 'bg-blue-100 font-semibold p-2 rounded cursor-pointer';
  const inactiveClass = 'p-2 rounded cursor-pointer hover:bg-gray-100';

  useEffect(() => {
    const fetchData = async () => {
      try {
        const resUser = await axios.get('/api/users/me', { headers: { Authorization: `Bearer ${token}` } });
        setUser(resUser.data);
        setForm(f => ({ ...f, name: resUser.data.name, email: resUser.data.email }));
        setNewEmail(resUser.data.email);

        const resAddr = await axios.get('/api/addresses', { headers: { Authorization: `Bearer ${token}` } });
        if (resAddr.data.length > 0) {
          const addr = resAddr.data[0];
          setAddressForm({ fullName: addr.fullName, phone: addr.phone, street: addr.street, district: addr.district, city: addr.city });
          setAddressId(addr._id);
        }
      } catch (err) {
        console.error('Lỗi khi tải dữ liệu Profile:', err);
      }
    };
    fetchData();
  }, [token]);

  const onFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setPreview(URL.createObjectURL(file));
      setForm({ ...form, avatar: file });
    }
  };

  const updateProfile = async () => {
    try {
      const formData = new FormData();
      formData.append('name', form.name);
      if (form.avatar) formData.append('avatar', form.avatar);

      const res = await axios.put('/api/users/me', formData, {
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'multipart/form-data' }
      });

      setUser(res.data.user);
      localStorage.setItem('user', JSON.stringify(res.data.user));
      window.location.reload();
    } catch (err) {
      setMessage('Có lỗi xảy ra!');
      setMessageClass('text-red-600');
    }
  };

  const changePassword = async () => {
    if (!form.currentPassword || !form.newPassword) {
      setMessage('Vui lòng nhập đầy đủ thông tin');
      setMessageClass('text-red-600');
      return;
    }
    try {
      const res = await axios.put('/api/users/change-password', { currentPassword: form.currentPassword, newPassword: form.newPassword }, { headers: { Authorization: `Bearer ${token}` } });
      if (res.data.success) {
        setMessage('Đổi mật khẩu thành công');
        setMessageClass('text-green-600');
        setForm({ ...form, currentPassword: '', newPassword: '' });
      } else {
        setMessage('Nhập sai mật khẩu cũ');
        setMessageClass('text-red-600');
      }
    } catch (err) {
      setMessage('Lỗi đổi mật khẩu');
      setMessageClass('text-red-600');
    }
  };

  const updateEmail = async () => {
    if (!newEmail || newEmail === user.email) {
      alert('Vui lòng nhập email mới hợp lệ!');
      return;
    }
    try {
      setLoadingEmail(true);
      await axios.put('/api/users/update-email', { email: newEmail }, { headers: { Authorization: `Bearer ${token}` } });
      setUser({ ...user, email: newEmail });
      localStorage.setItem('user', JSON.stringify({ ...user, email: newEmail }));
      alert('Email đã được cập nhật!');
    } catch (err) {
      alert('Lỗi: ' + (err.response?.data?.msg || 'Không thể cập nhật email'));
    } finally {
      setLoadingEmail(false);
    }
  };

  const saveAddress = async () => {
    try {
      if (addressId) {
        await axios.put(`/api/addresses/${addressId}`, addressForm, { headers: { Authorization: `Bearer ${token}` } });
      } else {
        const res = await axios.post('/api/addresses', addressForm, { headers: { Authorization: `Bearer ${token}` } });
        setAddressId(res.data._id);
      }
      alert('Lưu địa chỉ thành công!');
    } catch (err) {
      alert('Lỗi khi lưu địa chỉ!');
    }
  };

  return (
    <div className="flex flex-col md:flex-row gap-6 p-4">
      {/* Menu trái */}
      <div className="w-full md:w-1/3 bg-white rounded-xl shadow p-4 space-y-2">
        <div className={tab === 'info' ? activeClass : inactiveClass} onClick={() => setTab('info')}>Thông tin của tôi</div>
        <div className={tab === 'security' ? activeClass : inactiveClass} onClick={() => setTab('security')}>Email và mật khẩu</div>
        <div className={tab === 'address' ? activeClass : inactiveClass} onClick={() => setTab('address')}>Địa chỉ giao hàng</div>
      </div>

      {/* Nội dung phải */}
      <div className="w-full md:w-2/3 bg-white rounded-xl shadow p-6">
        {tab === 'info' && (
          <div className="space-y-6 min-h-[500px]">
            <h2 className="text-2xl font-bold text-gray-800">Cập nhật thông tin</h2>
            <div className="flex items-center gap-4">
              <img src={preview || `http://localhost:5000/${user.avatar || 'uploads/avatars/default-user.png'}`} className="w-24 h-24 rounded-full object-cover border" alt="Avatar" />
              <input type="file" onChange={onFileChange} />
            </div>
            <div>
              <label className="font-medium block mb-1">Tên người dùng</label>
              <input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="mt-1 block w-full border border-gray-300 rounded p-2 focus:outline-none focus:ring-2 focus:ring-blue-500" type="text" />
            </div>
            <button onClick={updateProfile} className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition">Lưu thay đổi</button>
          </div>
        )}

        {tab === 'security' && (
          <div className="space-y-6">
            <h2 className="text-2xl font-bold text-gray-800">Bảo mật tài khoản</h2>
            <div className="space-y-4">
              <div className="flex items-center gap-3 mb-2">
                <FontAwesomeIcon icon={['fas', 'envelope']} className="text-red-500 text-xl" />
                <span className="text-base text-3xl font-semibold text-gray-800">{user.email}</span>
              </div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Thay đổi gmail của tôi</label>
              <input value={newEmail} onChange={e => setNewEmail(e.target.value)} onFocus={() => setNewEmail('')} type="email" placeholder="Nhập email mới" className="mt-1 block w-full border border-gray-300 rounded p-2 focus:outline-none focus:ring-2 focus:ring-blue-500 mb-3" />
              <button onClick={updateEmail} disabled={loadingEmail} className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition">{loadingEmail ? 'Đang lưu...' : 'Lưu'}</button>
            </div>
            <div className="space-y-4 pt-4 border-t">
              <div>
                <label className="font-medium block mb-1">Thay đổi mật khẩu</label>
                <input value={form.currentPassword} onChange={e => setForm({ ...form, currentPassword: e.target.value })} type="password" placeholder="Nhập mật khẩu hiện tại" className="mt-1 block w-full border border-gray-300 rounded p-2 focus:outline-none focus:ring-2 focus:ring-blue-500" />
              </div>
              <div>
                <label className="font-medium block mb-1">Mật khẩu mới</label>
                <input value={form.newPassword} onChange={e => setForm({ ...form, newPassword: e.target.value })} type="password" placeholder="Nhập mật khẩu mới" className="mt-1 block w-full border border-gray-300 rounded p-2 focus:outline-none focus:ring-2 focus:ring-blue-500" />
              </div>
              <button onClick={changePassword} className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition">Lưu</button>
              {message && <p className={messageClass}>{message}</p>}
            </div>
          </div>
        )}

        {tab === 'address' && (
          <div className="space-y-6 min-h-[500px]">
            <h2 className="text-2xl font-bold text-gray-800">Địa chỉ giao hàng</h2>
            <div className="grid grid-cols-2 gap-4">
              <div><label className="block font-medium mb-1">Họ và tên</label><input value={addressForm.fullName} onChange={e => setAddressForm({ ...addressForm, fullName: e.target.value })} className="mt-1 block w-full border border-gray-300 rounded p-2" /></div>
              <div><label className="block font-medium mb-1">Số điện thoại</label><input value={addressForm.phone} onChange={e => setAddressForm({ ...addressForm, phone: e.target.value })} className="mt-1 block w-full border border-gray-300 rounded p-2" /></div>
            </div>
            <div><label className="block font-medium mb-1">Địa chỉ nhà</label><input value={addressForm.street} onChange={e => setAddressForm({ ...addressForm, street: e.target.value })} className="mt-1 block w-full border border-gray-300 rounded p-2" /></div>
            <div className="grid grid-cols-2 gap-4">
              <div><label className="block font-medium mb-1">Quận / Huyện</label><input value={addressForm.district} onChange={e => setAddressForm({ ...addressForm, district: e.target.value })} className="mt-1 block w-full border border-gray-300 rounded p-2" /></div>
              <div><label className="block font-medium mb-1">Thành phố</label><input value={addressForm.city} onChange={e => setAddressForm({ ...addressForm, city: e.target.value })} className="mt-1 block w-full border border-gray-300 rounded p-2" /></div>
            </div>
            <button onClick={saveAddress} className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700 transition">Lưu địa chỉ</button>
          </div>
        )}
      </div>
    </div>
  );
};

export default Profile;
