// frontend/src/components/Footer.vue
<template>
  <footer class="bg-gray-900 text-white py-10 mt-10">
    <div class="max-w-7xl mx-auto px-4 grid grid-cols-1 md:grid-cols-3 gap-8">
      <!-- Logo + Giới thiệu -->
      <div>
        <h2 class="text-2xl font-bold mb-4"> BookNest</h2>
        <p class="text-sm text-gray-300">
          Nền tảng mua sách trực tuyến với hàng ngàn đầu sách chất lượng, hỗ trợ người dùng 24/7.
        </p>
      </div>

      <!-- Liên kết -->
      <div>
        <h3 class="text-xl font-semibold mb-4">Liên kết</h3>
        <ul class="space-y-2 text-sm text-gray-300">
          <li><router-link to="/" class="hover:underline">Trang chủ</router-link></li>
          <li><router-link to="/books" class="hover:underline">Sách</router-link></li>
          <li><router-link to="/cart" class="hover:underline">Giỏ hàng</router-link></li>
          <li><router-link to="/profile" class="hover:underline">Tài khoản</router-link></li>
        </ul>
      </div>

      <!-- Liên hệ -->
      <div>
        <h3 class="text-xl font-semibold mb-4">Liên hệ</h3>
<ul class="text-sm text-gray-300 space-y-2">
  <li class="flex items-center gap-2">
    <i class="fas fa-phone-alt text-yellow-400"></i>
    Hotline: 0123 456 789
  </li>
  <li class="flex items-center gap-2">
    <i class="fas fa-envelope text-yellow-400"></i>
    Email: support@booknest.vn
  </li>
  <li class="flex items-center gap-2">
    <i class="fas fa-map-marker-alt text-yellow-400"></i>
    123 Nguyễn Văn Cừ, Q.5, TP.HCM
  </li>
</ul>
      </div>
    </div>

    <div class="mt-10 text-center text-gray-500 text-xs border-t border-gray-700 pt-4">
      © 2025 BookNest. All rights reserved.
    </div>
  </footer>
</template>

// frontend-react/src/components/Footer.jsx
import { Link } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

const Footer = () => {
    return (
        <footer className="bg-gray-900 text-white py-10 mt-10">
            <div className="max-w-7xl mx-auto px-4 grid grid-cols-1 md:grid-cols-3 gap-8">
                {/* Logo + Giới thiệu */}
                <div>
                    <h2 className="text-2xl font-bold mb-4">BookNest</h2>
                    <p className="text-sm text-gray-300">
                        Nền tảng mua sách trực tuyến với hàng ngàn đầu sách chất lượng, hỗ trợ người dùng 24/7.
                    </p>
                </div>

                {/* Liên kết */}
                <div>
                    <h3 className="text-xl font-semibold mb-4">Liên kết</h3>
                    <ul className="space-y-2 text-sm text-gray-300">
                        <li><Link to="/" className="hover:underline">Trang chủ</Link></li>
                        <li><Link to="/books" className="hover:underline">Sách</Link></li>
                        <li><Link to="/cart" className="hover:underline">Giỏ hàng</Link></li>
                        <li><Link to="/profile" className="hover:underline">Tài khoản</Link></li>
                    </ul>
                </div>

                {/* Liên hệ */}
                <div>
                    <h3 className="text-xl font-semibold mb-4">Liên hệ</h3>
                    <ul className="text-sm text-gray-300 space-y-2">
                        <li className="flex items-center gap-2">
                            <FontAwesomeIcon icon={['fas', 'phone-alt']} className="text-yellow-400" />
                            Hotline: 0123 456 789
                        </li>
                        <li className="flex items-center gap-2">
                            <FontAwesomeIcon icon={['fas', 'envelope']} className="text-yellow-400" />
                            Email: support@booknest.vn
                        </li>
                        <li className="flex items-center gap-2">
                            <FontAwesomeIcon icon={['fas', 'map-marker-alt']} className="text-yellow-400" />
                            123 Nguyễn Văn Cừ, Q.5, TP.HCM
                        </li>
                    </ul>
                </div>
            </div>

            <div className="mt-10 text-center text-gray-500 text-xs border-t border-gray-700 pt-4">
                © 2025 BookNest. All rights reserved.
            </div>
        </footer>
    );
};

export default Footer;
