// frontend/src/components/Navbar.vue
<template>
  <!-- Top bar -->
  <div class="hidden md:flex bg-gray-100 justify-end px-5 py-2 gap-3 text-sm relative">
    <template v-if="user">
      <!-- Avatar Dropdown -->
      <div class="relative" @click="toggleDropdown">
        <img
          :src="avatarUrl"
          alt="User Avatar"
          class="w-8 h-8 rounded-full mr-10 object-cover cursor-pointer border-2 border-gray-300"
        />

        <!-- Dropdown menu -->
        <div
          v-if="dropdownOpen"
          class="absolute right-0 mt-2 mr-10 w-48 bg-white rounded-md shadow-lg border z-[999]"
        >
          <div class="px-4 py-2 text-sm text-gray-700 font-semibold truncate">
            {{ user.name }}
          </div>
          <hr class="my-1" />
          <RouterLink
            to="/profile"
            class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
            @click="closeDropdown"
          >
            Hồ sơ cá nhân
          </RouterLink>

          
          <RouterLink
            to="/orders"
            class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
            @click="closeDropdown"
          >
            Lịch sử mua hàng
          </RouterLink>

          <button
            @click="logout"
            class="block w-full text-left px-4 py-2 text-sm text-red-600 hover:bg-gray-100"
          >
            Đăng xuất
          </button>
        </div>
      </div>
    </template>
    <template v-else>
      <RouterLink class="hover:underline font-medium" to="/register">Join Us</RouterLink>
      <RouterLink
        class="hover:underline font-medium border-l mr-10 border-gray-400 pl-3"
        to="/login"
      >Sign In</RouterLink>
    </template>
  </div>

  <!-- Navbar -->
  <nav class="bg-white sticky top-0 shadow py-3 z-50">
    <div class="container mx-auto flex items-center px-4 md:px-8 relative">
      <!-- Logo -->
      <RouterLink to="/" class="flex items-center  flex-shrink-0">
        <img src="@/assets/image/logo.png" alt="Logo" class="h-10 w-auto" />
      </RouterLink>

      <!-- Center navigation links -->
      <div
        class="hidden md:flex absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 gap-6 text-base font-medium text-gray-700"
      >
        <RouterLink to="/" class="hover:text-blue-600">Trang chủ</RouterLink>
        <RouterLink to="/books" class="hover:text-blue-600">Sách</RouterLink>
        <RouterLink to="/contact" class="hover:text-blue-600">Liên hệ</RouterLink>
      </div>

      <!-- Right section: Search + Icons -->
      <div class="hidden md:flex items-center ml-auto mr-8 gap-4">
        <!-- Search -->
    <!-- Input Search ở giữa -->
    <div class="flex-1 flex justify-center">
      <InputSearch />
    </div>

        <!-- Icons -->
        <RouterLink to="/favorites" class="text-gray-700 hover:text-blue-600 text-lg">
          <font-awesome-icon :icon="['far', 'heart']" />
        </RouterLink>

        <!-- Giỏ hàng với số lượng -->
        <RouterLink to="/cart" class="relative text-gray-700 hover:text-blue-600 text-xl">
          <font-awesome-icon :icon="['fas', 'bag-shopping']" />
          <span
            v-if="cartCount > 0"
            class="absolute -top-2 -right-2 bg-red-500 text-white text-xs rounded-full w-5 h-5 flex items-center justify-center"
          >
            {{ cartCount }}
          </span>
        </RouterLink>
      </div>

      <!-- Mobile menu toggle -->
      <button class="md:hidden text-black text-xl ml-4" @click="toggleMenu">
        <font-awesome-icon :icon="['fas', 'bars']" />
      </button>
    </div>

    <!-- Mobile menu -->
    <div
      class="md:hidden fixed top-0 right-0 h-full w-2/3 bg-white shadow-md z-40 transition-transform duration-300"
      :class="{ 'translate-x-0': menuOpen, 'translate-x-full': !menuOpen }"
    >
      <div class="flex items-center justify-between p-4 border-b">
        <h5 class="font-bold">Menu</h5>
        <button @click="toggleMenu" class="text-gray-500">
          <font-awesome-icon :icon="['fas', 'xmark']" class="text-xl" />
        </button>
      </div>

      <ul class="flex flex-col gap-4 p-4">
        <li>
          <RouterLink to="/" class="flex items-center text-black hover:underline" @click="toggleMenu">
            Trang chủ
          </RouterLink>
        </li>
        <li>
          <RouterLink to="/books" class="flex items-center text-black hover:underline" @click="toggleMenu">
            Sách
          </RouterLink>
        </li>
        <li>
          <RouterLink to="/contact" class="flex items-center text-black hover:underline" @click="toggleMenu">
            Liên hệ
          </RouterLink>
        </li>
        <li>
          <RouterLink to="/favorites" class="flex items-center text-black hover:underline" @click="toggleMenu">
            <font-awesome-icon :icon="['far', 'heart']" class="mr-2" />
            Yêu thích
          </RouterLink>
        </li>
        <li>
          <RouterLink to="/cart" class="flex items-center text-black hover:underline" @click="toggleMenu">
            <font-awesome-icon :icon="['fas', 'bag-shopping']" class="mr-2" />
            Giỏ hàng
          </RouterLink>
        </li>
        <li v-if="!user">
          <RouterLink to="/login" class="flex items-center text-black hover:underline" @click="toggleMenu">
            <font-awesome-icon :icon="['far', 'user']" class="mr-2" />
            Đăng nhập
          </RouterLink>
        </li>
        <li v-else>
          <button @click="logout" class="text-left text-black hover:underline">Đăng xuất</button>
        </li>
      </ul>
    </div>
  </nav>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRouter, RouterLink } from 'vue-router'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { cartCount, setCartCount } from '@/composables/cartStore'
import axios from 'axios'
import InputSearch from '@/components/InputSearch.vue'
const router = useRouter()

// Menu Toggle
const menuOpen = ref(false)
const toggleMenu = () => {
  menuOpen.value = !menuOpen.value
}

// Lấy user từ localStorage
const user = ref(null)
onMounted(() => {
  const stored = localStorage.getItem('user')
  if (stored) user.value = JSON.parse(stored)
})

// Avatar
const avatarUrl = computed(() => {
  if (!user.value) return ''
  const baseUrl = user.value.avatar
    ? `/${user.value.avatar}`
    : '/uploads/avatars/default-user.png'

  const timestamp = Date.now() // force refresh
  return `${baseUrl}?t=${timestamp}`
})

// Dropdown
const dropdownOpen = ref(false)
const toggleDropdown = () => (dropdownOpen.value = !dropdownOpen.value)
const closeDropdown = () => (dropdownOpen.value = false)
const handleClickOutside = (event) => {
  const dropdown = document.querySelector('.relative')
  if (dropdown && !dropdown.contains(event.target)) {
    dropdownOpen.value = false
  }
}
onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})
onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
})

// Logout
const logout = () => {
  localStorage.removeItem('user')
  localStorage.removeItem('token')
  user.value = null
  dropdownOpen.value = false
  router.push('/')
}

// Load số lượng giỏ hàng khi mount Navbar
const loadCartCount = async () => {
  const token = localStorage.getItem('token')
  if (!token) {
    setCartCount(0)
    return
  }
  try {
    const { data } = await axios.get('http://localhost:5000/api/cart', {
      headers: { Authorization: `Bearer ${token}` }
    })
    if (data && data.items) {
      const total = data.items.reduce((sum, item) => sum + item.quantity, 0)
      setCartCount(total)
    } else {
      setCartCount(0)
    }
  } catch (error) {
    setCartCount(0)
  }
}

onMounted(() => {
  loadCartCount()
})
</script>

// frontend-react/src/components/Navbar.jsx
import React, { useState, useEffect, useRef } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

// Components & Assets
import InputSearch from './InputSearch';
import logo from '../assets/image/logo.png';

// Stores
import { useAuthStore } from '../stores/auth';
import { useCartStore } from '../composables/cartStore';

const Navbar = () => {
    const navigate = useNavigate();

    // State quản lý UI
    const [menuOpen, setMenuOpen] = useState(false);
    const [dropdownOpen, setDropdownOpen] = useState(false);
    const [genres, setGenres] = useState([]);
    const [showGenres, setShowGenres] = useState(false);

    // Refs
    const dropdownRef = useRef(null);

    // Lấy dữ liệu từ Global Stores
    const { user, logout, token } = useAuthStore();
    const { cartCount, setCartCount } = useCartStore();

    // Đóng mở Menu & Dropdown
    const toggleMenu = () => setMenuOpen(!menuOpen);
    const toggleDropdown = () => setDropdownOpen(!dropdownOpen);
    const closeDropdown = () => setDropdownOpen(false);

    // Xử lý Avatar URL
    const getAvatarUrl = () => {
        if (!user) return '';
        // Thêm http://localhost:5000 nếu backend của bạn chạy ở cổng này
        return `http://localhost:5000/${user.avatar || 'uploads/avatars/default-user.png'}?t=${Date.now()}`;
    };

    // Lấy số lượng giỏ hàng
    const loadCartCount = async () => {
        if (!token) {
            setCartCount(0);
            return;
        }
        try {
            const { data } = await axios.get('http://localhost:5000/api/cart', {
                headers: { Authorization: `Bearer ${token}` }
            });
            const total = data.items?.reduce((sum, item) => sum + item.quantity, 0) || 0;
            setCartCount(total);
        } catch {
            setCartCount(0);
        }
    };

    // Đăng xuất
    const handleLogout = () => {
        logout(); // Hàm logout từ zustand store (sẽ tự xóa token/user localStorage)
        closeDropdown();
        navigate('/');
    };

    // Lấy danh sách thể loại
    const fetchGenres = async () => {
        try {
            const { data } = await axios.get('http://localhost:5000/api/books/genres');
            setGenres(data);
        } catch (err) {
            console.error('Lỗi khi tải thể loại:', err);
        }
    };

    // Điều hướng thể loại
    const goToGenre = (genre) => {
        navigate(`/books/view-all?genre=${encodeURIComponent(genre)}`);
        setShowGenres(false);
    };

    const goToGenreMobile = (genre) => {
        navigate(`/books/view-all?genre=${encodeURIComponent(genre)}`);
        setMenuOpen(false);
    };

    // Click outside để đóng dropdown user
    useEffect(() => {
        const handleClickOutside = (e) => {
            if (dropdownRef.current && !dropdownRef.current.contains(e.target)) {
                setDropdownOpen(false);
            }
        };
        document.addEventListener('mousedown', handleClickOutside);
        return () => {
            document.removeEventListener('mousedown', handleClickOutside);
        };
    }, []);

    // Khởi tạo data khi mount
    useEffect(() => {
        loadCartCount();
        fetchGenres();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [token]); // Chạy lại loadCartCount nếu token thay đổi (đăng nhập/đăng xuất)

    return (
        <>
            {/* ================= TOP BAR ================= */}
            <div className="bg-gray-100 px-5 py-2 text-sm flex justify-between items-center md:justify-end gap-3 relative">
                {/* Logo on small screen */}
                <Link to="/" className="md:hidden font-semibold text-lg bigger">BookNest</Link>

                {/* User dropdown or login/register */}
                <div className="flex items-center gap-3 ml-auto">
                    {user ? (
                        <div className="relative" ref={dropdownRef}>
                            <img
                                src={getAvatarUrl()}
                                alt="User Avatar"
                                onClick={toggleDropdown}
                                className="w-8 h-8 rounded-full object-cover cursor-pointer border-2 border-gray-300 bigger"
                                onError={(e) => { e.target.src = 'http://localhost:5000/uploads/avatars/default-user.png'; }}
                            />
                            {dropdownOpen && (
                                <div className="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg border z-[999]">
                                    <div className="px-4 py-2 text-sm text-gray-700 font-semibold truncate">
                                        {user.name || user.username}
                                    </div>
                                    <hr className="my-1" />
                                    <Link to="/profile" onClick={closeDropdown} className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
                                        Hồ sơ cá nhân
                                    </Link>
                                    <Link to="/orders" onClick={closeDropdown} className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
                                        Lịch sử mua hàng
                                    </Link>
                                    <button onClick={handleLogout} className="block w-full text-left px-4 py-2 text-sm text-red-600 hover:bg-gray-100">
                                        Đăng xuất
                                    </button>
                                </div>
                            )}
                        </div>
                    ) : (
                        <>
                            <Link className="hover:underline font-medium" to="/register">Join Us</Link>
                            <Link className="hover:underline font-medium border-l pl-3 border-gray-400" to="/login">Sign In</Link>
                        </>
                    )}
                </div>
            </div>

            {/* ================= NAVBAR CHÍNH ================= */}
            <nav className="bg-white sticky top-0 shadow py-3 z-50">
                <div className="container mx-auto flex items-center justify-between px-4 md:px-8">
                    {/* Logo */}
                    <Link to="/" className="flex items-center flex-shrink-0">
                        <img src={logo} alt="Logo" className="h-10 w-auto bigger-small" />
                    </Link>

                    {/* Center links (desktop) */}
                    <div className="hidden md:flex gap-6 text-base font-medium text-gray-700 relative">
                        <Link to="/" className="hover:text-blue-600">Trang chủ</Link>

                        {/* Thể loại Dropdown */}
                        <div
                            className="relative"
                            onMouseEnter={() => setShowGenres(true)}
                            onMouseLeave={() => setShowGenres(false)}
                        >
                            <span className="cursor-pointer hover:text-blue-600">Thể loại</span>
                            {/* Thay thế <transition> của Vue bằng conditional rendering đơn giản */}
                            {showGenres && (
                                <div className="absolute left-0 top-full mt-2 w-48 bg-white shadow-lg border rounded z-50 transition-opacity duration-300">
                                    <ul className="p-2 space-y-1">
                                        {genres.map(genre => (
                                            <li
                                                key={genre}
                                                className="cursor-pointer hover:text-blue-600 px-2 py-1"
                                                onClick={() => goToGenre(genre)}
                                            >
                                                {genre}
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            )}
                        </div>

                        <Link to="/books" className="hover:text-blue-600">Sách</Link>
                    </div>

                    {/* Search & icons (desktop) */}
                    <div className="hidden md:flex items-center gap-4">
                        <InputSearch />
                        <Link to="/favorites" className="text-gray-700 hover:text-red-600 text-lg bigger">
                            <FontAwesomeIcon icon={['far', 'heart']} />
                        </Link>
                        <Link to="/cart" className="relative text-gray-700 hover:text-green-600 text-xl bigger">
                            <FontAwesomeIcon icon={['fas', 'bag-shopping']} />
                            {cartCount > 0 && (
                                <span className="absolute -top-2 -right-2 bg-red-500 text-white text-xs rounded-full w-5 h-5 flex items-center justify-center">
                                    {cartCount}
                                </span>
                            )}
                        </Link>
                    </div>

                    {/* Mobile menu toggle button */}
                    <button className="md:hidden text-black text-xl ml-4" onClick={toggleMenu}>
                        <FontAwesomeIcon icon={['fas', 'bars']} />
                    </button>
                </div>

                {/* ================= MOBILE MENU ================= */}
                <div
                    className={`md:hidden fixed top-0 right-0 h-full w-full bg-white shadow-md z-40 transition-transform duration-300 ${menuOpen ? 'translate-x-0' : 'translate-x-full'}`}
                >
                    <div className="flex items-center justify-between p-4 border-b">
                        <img src={logo} alt="Logo" className="h-8 w-auto" />
                        <button onClick={toggleMenu} className="text-gray-500 hover:text-black">
                            <FontAwesomeIcon icon={['fas', 'xmark']} className="text-2xl" />
                        </button>
                    </div>
                    <ul className="flex flex-col gap-4 p-5 text-lg font-medium text-gray-800">
                        <li>
                            <Link to="/" onClick={toggleMenu} className="hover:text-blue-600 transition-colors">Trang chủ</Link>
                        </li>
                        <li>
                            <Link to="/books" onClick={toggleMenu} className="hover:text-blue-600 transition-colors">Sách</Link>
                        </li>

                        {/* Dropdown thể loại trên Mobile */}
                        <li>
                            <details>
                                <summary className="cursor-pointer hover:text-blue-600 transition-colors">Thể loại</summary>
                                <ul className="ml-4 mt-2 flex flex-col gap-2 text-base font-normal">
                                    {genres.map(genre => (
                                        <li key={genre}>
                                            <button onClick={() => goToGenreMobile(genre)} className="text-left hover:text-blue-500 transition-colors w-full">
                                                {genre}
                                            </button>
                                        </li>
                                    ))}
                                </ul>
                            </details>
                        </li>

                        <li>
                            <Link to="/favorites" onClick={toggleMenu} className="hover:text-blue-600 transition-colors">Yêu thích</Link>
                        </li>
                        <li>
                            <Link to="/cart" onClick={toggleMenu} className="hover:text-blue-600 transition-colors">Giỏ hàng</Link>
                        </li>
                        {!user && (
                            <li>
                                <Link to="/login" onClick={toggleMenu} className="hover:text-blue-600 transition-colors">Đăng nhập</Link>
                            </li>
                        )}
                    </ul>
                </div>
            </nav>
        </>
    );
};

export default Navbar;
